### ISSUE TITLE
[Errno 111] Connect call failed 

### ISSUE THREAD

**Issue by mercy3333** [Zelak312/flaresolverr-mitm-proxy#19]
So , i got this error  

"response": "<html><head>\n    <title>502 Bad Gateway</title>\n</head>\n<body>\n    <h1>502 Bad Gateway</h1>\n    <p>Multiple exceptions: [Errno 111] Connect call failed ('::1', 8090, 0, 0), [Errno 111] Connect call failed ('127.0.0.1', 8090)</p>\n\n</body></html>"

**Comment by Zelak312** [comment]
This error code indicates that there was an error in the upstream server.

Which means that you had an error with flaresolverr. Are you sure that what you are trying to reach exists? Have you tested flaresolverr on its how to see if it worked?

I would need to see the configuration you are using and what you are trying to access/how you are trying to do it so I could potentially reproduce it and look around to see what the problem is. But from the 502 error description. It seems to come from upstream which is normally flaresolverr in this case

**Comment by Zelak312** [comment]
Closing this issue since it's been a month now with no response

**Comment by Victordmz** [comment]
I'm having the same error.

Just the default config
```---
version: "2.1"
services:
  flaresolverr-mitm-proxy:
    image: ghcr.io/zelak312/flaresolverr-mitm-proxy:latest
    container_name: flaresolverr-mitm-proxy
    restart: unless-stopped
    environment:
      - PROXY=http://localhost:8090

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - 8191:8191
    restart: unless-stopped
```

and the default script
```
import requests

url = "http://localhost:8191/v1"

headers = {
    "Content-Type": "application/json"
}

data = {
    "cmd": "request.post",
    "url": "https://httpbin.org/post?$$headers[]=Authorization:mytoken",
    "maxTimeout": 60000,
    "proxy": {
        "url": "flaresolverr-mitm-proxy:8080"
    },
    "postData": "$$post=eyJ0ZXN0IjoibmljZSIsImFycmF5IjpbImxvbCJdLCJuZXN0ZWQiOnsieWVldCI6ICJvb2YifSwibnVtYmVyIjo0fQ=="
}

response = requests.post(url, headers=headers, json=data)

print(response.text)
```

Response:
```
{"status": "ok", "message": "Challenge not detected!", "solution": {"url": "https://httpbin.org/post?$$headers[]=Authorization:mytoken", "status": 200, "cookies": [], "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36", "headers": {}, "response": "<html><head>\n    <title>502 Bad Gateway</title>\n</head>\n<body>\n    <h1>502 Bad Gateway</h1>\n    <p>[Errno 111] Connect call failed ('0.0.0.0', 8090)</p>\n\n</body></html>"}, "startTimestamp": ..., "endTimestamp": ..., "version": "3.3.21"}
```

**Comment by Zelak312** [comment]
Ah, my docker example is wrong. The issue is really that mitm can't contact the upstream proxy which in this case should be flaresolverr. If you look at the ports exposed by flaresolverr's service in the compose, it is 8191 but the PROXY environment variable in mitm flaresolverr is set to port 8090 at the end of the url. It should be 8191 so it is able to reach flaresolverr. I will change this example so that is fixed

**Comment by Victordmz** [comment]
Hi, thank you for your update. I tried the new docker-compose, with this result (nothing else changed about my code):
```
{"status": "ok", "message": "Challenge not detected!", "solution": {"url": "https://httpbin.org/post?$$headers[]=Authorization:mytoken", "status": 200, "cookies": [], "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36", "headers": {}, "response": "<html><head>\n    <title>502 Bad Gateway</title>\n</head>\n<body>\n    <h1>502 Bad Gateway</h1>\n    <p>Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 8191), [Errno 99] Cannot assign requested address</p>\n\n</body></html>"}, "startTimestamp": ..., "endTimestamp": ..., "version": "3.3.21"}
```

I thought maybe changing the proxy address to http://flaresolverr:8191 might help, but I get this result:
```
{"status": "ok", "message": "Challenge not detected!", "solution": {"url": "https://httpbin.org/post?$$headers[]=Authorization:mytoken", "status": 200, "cookies": [], "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36", "headers": {}, "response": "<html><head>\n    <title>502 Bad Gateway</title>\n</head>\n<body>\n    <h1>502 Bad Gateway</h1>\n    <p>Upstream proxy flaresolverr:8191 refused HTTP CONNECT request: 404 Not Found</p>\n\n</body></html>"}, "startTimestamp": ..., "endTimestamp": ..., "version": "3.3.21"}
```

**Comment by Zelak312** [comment]
I see what is happening.
it's a been a little since I had to do anything on this project so I was quite rusty with it and what I said yesterday is incorrect. the PROXY environment variable is to tell mitm to use an upstream proxy.
The way it works is that the curl example calls flaresolverr which uses flaresolverr mitm as the proxy.
so it goes curl -> flarsolverr -> flaresolverr mitm -> flaresolverr -> curl response.

but using PROXY is so people can also use their own proxy upstream so it will do
curl -> flaresolverr -> flaresolverr mitm -> their proxy -> ... all the way back to curl

so the issue is that flaresolverr mitm tries to use the localhost:8080 proxy after it receives the request. I believe that you don't have an upstream proxy so you should just remove this environment variable it should look like

```
version: "2.1"
services:
  flaresolverr-mitm-proxy:
    image: ghcr.io/zelak312/flaresolverr-mitm-proxy:latest
    container_name: flaresolverr-mitm-proxy
    restart: unless-stopped

  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - 8191:8191
    restart: unless-stopped
```

**Comment by Victordmz** [comment]
That makes a lot of sense. Thank you, it's working perfectly fine now.
